# Generated by Django 4.1.4 on 2022-12-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompaniy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.IntegerField()),
                ('cars', models.IntegerField()),
                ('filials', models.IntegerField()),
                ('transtort_companiy', models.IntegerField()),
                ('year', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
