# Generated by Django 4.1.4 on 2022-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompaniy',
            name='clients',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
