# Generated by Django 4.1.4 on 2022-12-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_steps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_step',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
